TDSMaps = {
    Version = "0.0",Author = "Tseting-nil",
	Regular = {
		AbandonedCity = {
			name = "Abandoned City",
			Easy = {Tower = {},Author = "",Script = "",},
			Casual = {Tower = {},Author = "",Script = "",},
			Intermediate = {Tower = {},Author = "",Script = "",},
			Molten = {Tower = {},Author = "",Script = "",},
			Fallen = {Tower = {},Author = "",Script = "",},
		},
		AutumnFalling = {
			name = "Autumn Falling",
			Easy = {Tower = {},Author = "",Script = "",},
			Casual = {Tower = {},Author = "",Script = "",},
			Intermediate = {Tower = {},Author = "",Script = "",},
			Molten = {Tower = {},Author = "",Script = "",},
			Fallen = {Tower = {},Author = "",Script = "",},
		},
		Crossroads = {
			name = "Crossroads",
			Easy = {Tower = {},Author = "",Script = "",},
			Casual = {Tower = {},Author = "",Script = "",},
			Intermediate = {Tower = {},Author = "",Script = "",},
			Molten = {Tower = {},Author = "",Script = "",},
			Fallen = {Tower = {},Author = "",Script = "",},
		},
		ForestCamp = {
			name = "Forest Camp",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		FungiIsland = {
			name = "Fungi Island",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		GrassIsle = {
			name = "Grass Isle",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Harbor = {
			name = "Harbor",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Necropolis = {
			name = "Necropolis",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Portland = {
			name = "Portland",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		RetroCrossroads = {
			name = "Retro Crossroads",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		RetroStainedTemple = {
			name = "Retro Stained Temple",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		RocketArena = {
			name = "Rocket Arena",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		SkyIslands = {
			name = "Sky Islands",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		TropicalIsles = {
			name = "Tropical Isles",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Toyboard = {
			name = "Toyboard",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		UTurn = {
			name = "U-Turn",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		ChessBoard = {
			name = "Chess Board",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		CoralDeep = {
			name = "Coral Deep",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		CrystalCave = {
			name = "Crystal Cave",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		CyberCity = {
			name = "Cyber City",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		DesertedVillage = {
			name = "Deserted Village",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		FarmLands = {
			name = "Farm Lands",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		FourSeasons = {
			name = "Four Seasons",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Lighthaos = {
			name = "Lighthaos",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Marshlands = {
			name = "Marshlands",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		MedievalTimes = {
			name = "Medieval Times",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Meltdown = {
			name = "Meltdown",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		MoonBase = {
			name = "Moon Base",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Nether = {
			name = "Nether",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		NightStation = {
			name = "Night Station",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		RetroLighthouse = {
			name = "Retro Lighthouse",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		RubyEscort = {
			name = "Ruby Escort",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Simplicity = {
			name = "Simplicity",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		SpringFever = {
			name = "Spring Fever",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		StainedTemple = {
			name = "Stained Temple",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		SugarRush = {
			name = "Sugar Rush",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		SummerCastle = {
			name = "Summer Castle",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		TropicalIndustries = {
			name = "Tropical Industries",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		WinterBridges = {
			name = "Winter Bridges",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		WreckedBattlefield = {
			name = "Wrecked Battlefield",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		WreckedBattlefieldII = {
			name = "Wrecked Battlefield II",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		AbyssalTrench = {
			name = "Abyssal Trench",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		CandyValley = {
			name = "Candy Valley",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		Cataclysm = {
			name = "Cataclysm",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		ConstructionCrazy = {
			name = "Construction Crazy",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		DustyBridges = {
			name = "Dusty Bridges",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		ForgettenDocks = {
			name = "Forgetten Docks",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		GildedPath = {
			name = "Gilded Path",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		RetroTheHeights = {
			name = "Retro The Heights",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		RetroZone = {
			name = "Retro Zone",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		SacredMountains = {
			name = "Sacred Mountains",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		TheHeights = {
			name = "The Heights",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		WinterAbyss = {
			name = "Winter Abyss",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		BlackSpotExchange = {
			name = "Black Spot Exchange",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		DeadAhead = {
			name = "Dead Ahead",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		HotSpot = {
			name = "Hot Spot",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		InfernalAbyss = {
			name = "Infernal Abyss",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		LayBy = {
			name = "Lay By",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		MasonArch = {
			name = "Mason Arch",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		SpaceCity = {
			name = "Space City",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
		WinterStronghold = {
			name = "Winter Stronghold",
			Easy = { Tower = {}, Author = "", Script = "" },
			Casual = { Tower = {}, Author = "", Script = "" },
			Intermediate = { Tower = {}, Author = "", Script = "" },
			Molten = { Tower = {}, Author = "", Script = "" },
			Fallen = { Tower = {}, Author = "", Script = "" },
		},
	},
	Special = {
		BadlandsII = {
			name = "Badlands II", Tower = {},Author = "", Script = "" },
		PizzaParty = {
			name = "Pizza Party", Tower = {},Author = "", Script = "" },
		PollutedWastelandII = {
			name = "Polluted Wasteland II", Tower = {},Author = "", Script = "" }
	},
	Hardcore = {
		AutumnFalling = { name = "Autumn Falling", Tower = {},Author = "", Script = "" },
		Crossroads = { name = "Crossroads", Tower = {},Author = "", Script = "" },
		Harbor = { name = "Harbor", Tower = {},Author = "", Script = "" },
		CyberCity = { name = "Cyber City", Tower = {},Author = "", Script = "" },
		FourSeasons = { name = "Four Seasons", Tower = {},Author = "", Script = "" },
		Marshlands = { name = "Marshlands", Tower = {},Author = "", Script = "" },
		MedievalTimes = { name = "Medieval Times", Tower = {},Author = "", Script = "" },
		Nether = { name = "Nether", Tower = {},Author = "", Script = "" },
		NightStation = { name = "Night Station", Tower = {},Author = "", Script = "" },
		WreckedBattlefield = { name = "Wrecked Battlefield", Tower = {},Author = "", Script = "" },
		WreckedBattlefieldII = { name = "Wrecked Battlefield II", Tower = {},Author = "", Script = "" },
		BlackSpotExchange = { name = "Black Spot Exchange", Tower = {},Author = "", Script = "" },
		HotSpot = { name = "Hot Spot", Tower = {},Author = "", Script = "" },
		InfernalAbyss = { name = "Infernal Abyss", Tower = {},Author = "", Script = "" },
		LegacySpaceCity = { name = "Legacy Space City", Tower = {},Author = "", Script = "" },
		SpaceCity = { name = "Space City", Tower = {},Author = "", Script = "" },
		UnknownGarden = { name = "Unknown Garden", Tower = {},Author = "", Script = "" }
	}
}

return TDSMaps
