TDSMaps = {
	Regular = {
		AbandonedCity = {
			Name = "Abandoned City",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		AutumnFalling = {
			Name = "Autumn Falling",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Crossroads = {
			Name = "Crossroads",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		ForestCamp = {
			Name = "Forest Camp",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		FungiIsland = {
			Name = "Fungi Island",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		GrassIsle = {
			Name = "Grass Isle",
			Easy_Script = "https://raw.githubusercontent.com/Tseting-nil/Tower-Defense-Simulator/refs/heads/main/MapscriptURL/Grass%20Isle/Easy/Script.lua",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Harbor = {
			Name = "Harbor",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Necropolis = {
			Name = "Necropolis",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Portland = {
			Name = "Portland",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		RetroCrossroads = {
			Name = "Retro Crossroads",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		RetroStainedTemple = {
			Name = "Retro Stained Temple",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		RocketArena = {
			Name = "Rocket Arena",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		SkyIslands = {
			Name = "Sky Islands",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		TropicalIsles = {
			Name = "Tropical Isles",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Toyboard = {
			Name = "Toyboard",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		UTurn = {
			Name = "U-Turn",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		ChessBoard = {
			Name = "Chess Board",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		CoralDeep = {
			Name = "Coral Deep",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		CrystalCave = {
			Name = "Crystal Cave",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		CyberCity = {
			Name = "Cyber City",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		DesertedVillage = {
			Name = "Deserted Village",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		FarmLands = {
			Name = "Farm Lands",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		FourSeasons = {
			Name = "Four Seasons",
			Easy_Script = "https://raw.githubusercontent.com/Tseting-nil/Tower-Defense-Simulator/refs/heads/main/MapscriptURL/Four%20Seasons/Easy/Script.lua",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Iceville = {
			Name = "Iceville",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Lighthaos = {
			Name = "Lighthaos",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Marshlands = {
			Name = "Marshlands",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		MedievalTimes = {
			Name = "Medieval Times",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Meltdown = {
			Name = "Meltdown",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		MoonBase = {
			Name = "Moon Base",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Nether = {
			Name = "Nether",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		NightStation = {
			Name = "Night Station",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		RetroLighthouse = {
			Name = "Retro Lighthouse",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		RubyEscort = {
			Name = "Ruby Escort",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Simplicity = {
			Name = "Simplicity",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		SpringFever = {
			Name = "Spring Fever",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		StainedTemple = {
			Name = "Stained Temple",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		SugarRush = {
			Name = "Sugar Rush",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		SummerCastle = {
			Name = "Summer Castle",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		TropicalIndustries = {
			Name = "Tropical Industries",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		WinterBridges = {
			Name = "Winter Bridges",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		WreckedBattlefield = {
			Name = "Wrecked Battlefield",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		WreckedBattlefieldII = {
			Name = "Wrecked Battlefield II",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		AbyssalTrench = {
			Name = "Abyssal Trench",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		CandyValley = {
			Name = "Candy Valley",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		Cataclysm = {
			Name = "Cataclysm",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		ConstructionCrazy = {
			Name = "Construction Crazy",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		DustyBridges = {
			Name = "Dusty Bridges",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		ForgettenDocks = {
			Name = "Forgetten Docks",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		GildedPath = {
			Name = "Gilded Path",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		RetroTheHeights = {
			Name = "Retro The Heights",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		RetroZone = {
			Name = "Retro Zone",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		SacredMountains = {
			Name = "Sacred Mountains",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		TheHeights = {
			Name = "The Heights",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		WinterAbyss = {
			Name = "Winter Abyss",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		BlackSpotExchange = {
			Name = "Black Spot Exchange",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		DeadAhead = {
			Name = "Dead Ahead",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		HotSpot = {
			Name = "Hot Spot",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		InfernalAbyss = {
			Name = "Infernal Abyss",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		LayBy = {
			Name = "Lay By",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		MasonArch = {
			Name = "Mason Arch",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		SpaceCity = {
			Name = "Space City",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
		WinterStronghold = {
			Name = "Winter Stronghold",
			Easy_Script = "",
			Casual_Script = "",
			Intermediate_Script = "",
			Molten_Script = "",
			Fallen_Script = "",
		},
	},
	Special = {
		BadlandsII = {
			Name = "Badlands II",
			Script = "",
		},
		PizzaParty = {
			Name = "Pizza Party",
			Script = "",
		},
		PollutedWastelandII = {
			Name = "Polluted Wasteland II",
			Script = "",
		},
	},
	Hardcore = {
		AutumnFalling = {
			Name = "Autumn Falling",
			Script = "",
		},
		Crossroads = {
			Name = "Crossroads",
			Script = "",
		},
		Harbor = {
			Name = "Harbor",
			Script = "",
		},
		CyberCity = {
			Name = "Cyber City",
			Script = "",
		},
		FourSeasons = {
			Name = "Four Seasons",
			Script = "",
		},
		Marshlands = {
			Name = "Marshlands",
			Script = "",
		},
		MedievalTimes = {
			Name = "Medieval Times",
			Script = "",
		},
		Nether = {
			Name = "Nether",
			Script = "",
		},
		NightStation = {
			Name = "Night Station",
			Script = "",
		},
		WreckedBattlefield = {
			Name = "Wrecked Battlefield",
			Script = "",
		},
		WreckedBattlefieldII = {
			Name = "Wrecked Battlefield II",
			Script = "",
		},
		BlackSpotExchange = {
			Name = "Black Spot Exchange",
			Script = "",
		},
		HotSpot = {
			Name = "Hot Spot",
			Script = "",
		},
		InfernalAbyss = {
			Name = "Infernal Abyss",
			Script = "",
		},
		LegacySpaceCity = {
			Name = "Legacy Space City",
			Script = "",
		},
		SpaceCity = {
			Name = "Space City",
			Script = "",
		},
		UnknownGarden = {
			Name = "Unknown Garden",
			Script = "",
		},
	},
}

return TDSMaps