TDSMaps = {
    Version = "0.0",Author = "Tseting-nil",
	Regular = {
		AbandonedCity = { name = "Abandoned City", Script = "" },
		AutumnFalling = { name = "Autumn Falling", Script = "" },
		Crossroads = { name = "Crossroads", Script = "" },
		ForestCamp = { name = "Forest Camp", Script = "" },
		FungiIsland = { name = "Fungi Island", Script = "" },
		GrassIsle = { name = "Grass Isle", Script = "" },
		Harbor = { name = "Harbor", Script = "" },
		Necropolis = { name = "Necropolis", Script = "" },
		Portland = { name = "Portland", Script = "" },
		RetroCrossroads = { name = "Retro Crossroads", Script = "" },
		RetroStainedTemple = { name = "Retro Stained Temple", Script = "" },
		RocketArena = { name = "Rocket Arena", Script = "" },
		SkyIslands = { name = "Sky Islands", Script = "" },
		TropicalIsles = { name = "Tropical Isles", Script = "" },
		Toyboard = { name = "Toyboard", Script = "" },
		UTurn = { name = "U-Turn", Script = "" },
		ChessBoard = { name = "Chess Board", Script = "" },
		CoralDeep = { name = "Coral Deep", Script = "" },
		CrystalCave = { name = "Crystal Cave", Script = "" },
		CyberCity = { name = "Cyber City", Script = "" },
		DesertedVillage = { name = "Deserted Village", Script = "" },
		FarmLands = { name = "Farm Lands", Script = "" },
		FourSeasons = { name = "Four Seasons", Script = "製作中" },
		Lighthaos = { name = "Lighthaos", Script = "" },
		Marshlands = { name = "Marshlands", Script = "" },
		MedievalTimes = { name = "Medieval Times", Script = "" },
		Meltdown = { name = "Meltdown", Script = "" },
		MoonBase = { name = "Moon Base", Script = "" },
		Nether = { name = "Nether", Script = "" },
		NightStation = { name = "Night Station", Script = "" },
		RetroLighthouse = { name = "Retro Lighthouse", Script = "" },
		RubyEscort = { name = "Ruby Escort", Script = "" },
		Simplicity = { name = "Simplicity", Script = "" },
		SpringFever = { name = "Spring Fever", Script = "" },
		StainedTemple = { name = "Stained Temple", Script = "" },
		SugarRush = { name = "Sugar Rush", Script = "" },
		SummerCastle = { name = "Summer Castle", Script = "" },
		TropicalIndustries = { name = "Tropical Industries", Script = "" },
		WinterBridges = { name = "Winter Bridges", Script = "" },
		WreckedBattlefield = { name = "Wrecked Battlefield", Script = "" },
		WreckedBattlefieldII = { name = "Wrecked Battlefield II", Script = "" },
		AbyssalTrench = { name = "Abyssal Trench", Script = "" },
		CandyValley = { name = "Candy Valley", Script = "" },
		Cataclysm = { name = "Cataclysm", Script = "" },
		ConstructionCrazy = { name = "Construction Crazy", Script = "" },
		DustyBridges = { name = "Dusty Bridges", Script = "" },
		ForgettenDocks = { name = "Forgetten Docks", Script = "" },
		GildedPath = { name = "Gilded Path", Script = "" },
		RetroTheHeights = { name = "Retro The Heights", Script = "" },
		RetroZone = { name = "Retro Zone", Script = "" },
		SacredMountains = { name = "Sacred Mountains", Script = "" },
		TheHeights = { name = "The Heights", Script = "" },
		WinterAbyss = { name = "Winter Abyss", Script = "" },
		BlackSpotExchange = { name = "Black Spot Exchange", Script = "" },
		DeadAhead = { name = "Dead Ahead", Script = "" },
		HotSpot = { name = "Hot Spot", Script = "" },
		InfernalAbyss = { name = "Infernal Abyss", Script = "" },
		LayBy = { name = "Lay By", Script = "" },
		MasonArch = { name = "Mason Arch", Script = "" },
		SpaceCity = { name = "Space City", Script = "" },
		WinterStronghold = { name = "Winter Stronghold", Script = "" }
	},
	Special = {
		BadlandsII = { name = "Badlands II", Script = "" },
		PizzaParty = { name = "Pizza Party", Script = "" },
		PollutedWastelandII = { name = "Polluted Wasteland II", Script = "" }
	},
	Hardcore = {
		AutumnFalling = { name = "Autumn Falling", script = "" },
		Crossroads = { name = "Crossroads", script = "" },
		Harbor = { name = "Harbor", script = "" },
		CyberCity = { name = "Cyber City", script = "" },
		FourSeasons = { name = "Four Seasons", script = "" },
		Marshlands = { name = "Marshlands", script = "" },
		MedievalTimes = { name = "Medieval Times", script = "" },
		Nether = { name = "Nether", script = "" },
		NightStation = { name = "Night Station", script = "" },
		WreckedBattlefield = { name = "Wrecked Battlefield", script = "" },
		WreckedBattlefieldII = { name = "Wrecked Battlefield II", script = "" },
		BlackSpotExchange = { name = "Black Spot Exchange", script = "" },
		HotSpot = { name = "Hot Spot", script = "" },
		InfernalAbyss = { name = "Infernal Abyss", script = "" },
		LegacySpaceCity = { name = "Legacy Space City", script = "" },
		SpaceCity = { name = "Space City", script = "" },
		UnknownGarden = { name = "Unknown Garden", script = "" }
	}
}

return TDSMaps
